config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'
  get 'reservations/create'
  get 'reservations/destroy'
  get 'search', to: "books#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homepage#index'


  resources :books do
    resource :reservations, only: [:new, :create, :destroy]
  end 
  devise_for :users, :controllers => { :omniauth_callbacks =>"users/omniauth_callbacks", :registrations => "users/registrations"}
  resources :users, only: [:show]

  resources :reservations do
    put :is_confirmed, on: :member
    put :is_deleted, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  acts_as_user :roles => [ :library, :reader]
  def self.from_omniauth(auth) 
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
          
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(access_token)

    data = access_token.info
    user = User.where(email: data['email']).first
     unless user
    
      user = User.create( email: data['email'],password: Devise.friendly_token[0,20])
     end
    user
  end

  def is_library?
    return (self.roles_mask & 1) == 1
  end

  def set_library
    self.roles_mask = (self.roles_mask | 1)
    self.save
  end

  def unset_library
    self.roles_mask = (self.roles_mask & 1)
    self.save
  end

  def is_reader?
    return (self.roles_mask & 2) == 2
  end

  def set_reader
    self.roles_mask = (self.roles_mask | 2)
    self.save
  end

  def unset_reader
    self.roles_mask = (self.roles_mask & 1)
    self.save
  end


  validates :address, :city, presence: true, if: :check_role?

  def check_role?
    roles_mask==1
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.from_omniauth(request.env["omniauth.auth"])
     if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
       set_flash_message(:notice, :success, :kind => "Facebook") 
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
     end
    end

    def google_oauth2
     @user = User.from_omniauth(request.env['omniauth.auth'])
        
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success',kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    end
    
    def failure
     redirect_to root_path
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters
    protected
    
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:email, :password, :created_at, :updated_at, :provider, :uid, :roles_mask, :name, :username, :address, :city)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :created_at, :updated_at, :provider, :uid, :roles_mask, :name, :username, :address, :city)
    end
  end
 
    def update_resource(resource, params)
        resource.update_without_password(params)
    end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user= User.find(params[:id])
        @book=Book.all
        @reservation=Reservation.all
    end

    def edit

    end
end

app/views/users/_library.html.erb
<div class="container">
  <h2> Library profile </h2>
    <div class="row">
      <div class="col">
        <%= image_tag 'library.png',style:"width:60%"%>
      </div>
      <div class="col-8">
    

    

      <div class="card" align="center" style="width: 100%">
          <br>
          <p>Name: <%= current_user.name %></p>
          <br>
          <p>Email: <%= current_user.email %></p>
          <br>
          <p>Username: <%= current_user.username %></p>
          <br>
          <p>Address: <%= current_user.address %></p>
          <br>
          <p>City: <%= current_user.city %></p>
          <br><br>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark' %> <br>
      </div>
    </div>
  </div>

  <hr>
  <%= button_to 'Add a book', new_book_path, method: :get, class: "btn btn-outline-dark"%>

  <br><br>
  <div class="card">
  <b>Available books:</b>
  <table>
  <% @counter1=0 %>
  <% @book.each do |book| %>  
    <tr>
    <% @current_book=Reservation.where(:book_id => book.id) %>  
    <% if @current_book.length==0 or @current_book[0][:confirmed]!=1 and book.owner==current_user.id%>
      <% @counter1+=1 %>
      <div class="row">
        <div class="col"> <li>Title: <%= book.title %> </div>
        <div class="col"><%= button_to book_path(book.id), class: 'btn bg-transparent', method: :get do%><i class="fa fa-info-circle fa-lg"></i><%end%></li></div>
      </div>
    <% end %>
    </tr>
  <% end %>
  <%if @counter1==0 %>
    <div class="col"> No available book  yet.. </div>
  <%end%>
  <br>
  </table>
  </div>
  <br><hr><br>

  <div class="card">
  <b>Borrowed books:</b>
  <table>
  <% @counter2=0 %>
  <% @reservation.each do |reservation| %>  
    <tr>
    <% @current_book=Book.where(:id => reservation.book_id) %>
    <% if @current_book[0][:owner]==current_user.id and reservation.confirmed==1%>  
      <% @counter2+=1 %>
      <div class="row">
        <div class="col"> <li>Title: <%= @current_book[0][:title] %> </div>
        <div class="col"> Requested by: <%= User.find(reservation[:user_id]).username %> </div>
        <% if reservation.comments!="" %>
          <div class="col">Notes: <%= reservation.comments %> </div>
        <% end %>
        <div class="col"> <%= button_to 'Set as available', reservation, method: :delete, class: 'btn btn-outline-dark' %> </li></div>
        <div class="col"><%= button_to book_path(@current_book[0][:id]), class: 'btn bg-transparent', method: :get do%><i class="fa fa-info-circle fa-lg"></i><%end%></li></div></li>
      </div>
    <% end %>
    </tr>
  <% end %>
  <%if @counter2==0 %>
    <div class="col"> No borrowed book  yet.. </div>
  <%end%>
  <br>
  </table>
  </div>
  <br><hr><br>


  <div class="card">
  <b>Pending requests:</b>
  <tr>
  <table>
  <% @counter3=0 %>
  <% @reservation.each do |reservation| %>  
    <tr>
    <% @current_book=Book.where(:id => reservation.book_id) %>
    <% if @current_book[0][:owner]==current_user.id and reservation.confirmed==0%>
      <% @counter3+=1 %>
      <div class="row">
        <div class="col"> <li> Title: <%= @current_book[0][:title] %> </div>
        <div class="col"> Requested by: <%= User.find(reservation[:user_id]).username %>  </div>
         <% if reservation.comments!="" %>
          <div class="col">Notes: <%= reservation.comments %> </div>
        <% end %>
        <div class="col"> <%= button_to 'Accept', is_confirmed_reservation_path(reservation) , :method => :put, class: "btn btn-success"%></div>
        <div class="col"> <%= button_to 'Decline', is_deleted_reservation_path(reservation) , :method => :put, class: "btn btn-danger" %></div>
      </div>
    <% end %>
    </tr>
  <% end %>
  <%if @counter3==0 %>
      <div class="col"> No pending request yet.. </div>
    <%end%>
  <br>
  </table>
</div>

app/views/users/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <div class="container-fluid"> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      
      <div>
      <div class="dropdown">
      <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      <%= image_tag "user.png", style:"width:50px" %>
      Account
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><%= button_to 'Profile', current_user, method: :get, class: "btn"%></li><hr>
        <li><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "btn"%></li>
      </ul>
      </div>

    </div>
    <div class="row">
    <div class="col">
    <%= button_to root_path, :method => :get, class: "btn" do%><i class="fa fa-arrow-circle-left fa-2x"></i>&emsp; Back to homepage<%end%>
    </div>
    </div>
  </div>
</nav>

app/views/users/_reader.html.erb
<div class="container">
  <h2> Reader profile </h2>
    <div class="row">
      <div class="col">
        <%= image_tag 'user.png',style:"width:60%"%>
      </div>
      <div class="col-8">
    

    

      <div class="card" align= "center" style="width: 100%">
          <br>
          <p>Name: <%= current_user.name %></p>
          <br>
          <p>Email: <%= current_user.email %></p>
          <br>
          <p>Username: <%= current_user.username %></p>
          <br>
          <% if current_user.roles_mask==1%>
            <p>Address: <%= current_user.address %></p>
          <% end %>
          <br><br>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark' %>
          <br>
      </div>
    </div>
  </div>


  <br><br>
  <div class="card">
  <b>Reserved books:</b>
  <table>
  <% @counter1=0 %>  
  <% @reservation.each do |reservation| %>  
    <tr>
    <% if reservation.user_id==current_user.id and reservation.confirmed==1%>  
    <% @counter1+=1 %>  
      <% @current_book=Book.where(:id => reservation.book_id) %>  
      <div class="row">
        <div class="col"> <li>Title: <%= @current_book[0][:title] %> </div>
         <% if reservation.comments!="" %>
          <div class="col">Notes: <%= reservation.comments %> </div>
        <% end %>
        <div class="col"> <%= button_to 'Delete', reservation, method: :delete, class: 'btn btn-danger' %></div>
        <div class="col"><%= button_to book_path(@current_book[0][:id]), class: 'btn bg-transparent', method: :get do%><i class="fa fa-info-circle fa-lg"></i><%end%></li></div></li>
    <% end %>
    </tr>
  <% end %>
  <%if @counter1==0 %>
    <div class="col"> No reserved book yet.. </div>
  <%end%>
  </table>
  </div>
  <br><hr><br>

  <div class="card">
  <b>Pending requests:</b>
  <table>
  <% @counter2=0 %>  
  <% @reservation.each do |reservation| %>  
    <tr>
    <% if reservation.user_id==current_user.id and reservation.confirmed==0%>  
    <% @counter2+=1 %>  
      <% @current_book=Book.where(:id => reservation.book_id) %>  
      <div class="row">
        <div class="col"><li> Title: <%= @current_book[0][:title] %> </div>
         <% if reservation.comments!="" %>
          <div class="col">Notes: <%= reservation.comments %> </div>
        <% end %>
        <div class="col"> <%= button_to 'Cancel', reservation, method: :delete, class: 'btn btn-danger' %> </li></div>
        <div class="col"><%= button_to book_path(@current_book[0][:id]), class: 'btn bg-transparent', method: :get do%><i class="fa fa-info-circle fa-lg"></i><%end%></li></div></li>
    <% end %>
    </tr>
  <% end %>
  <%if @counter2==0 %>
    <div class="col"> No pending request yet.. </div>
  <%end%>
  </table>
  </div>
  <br><hr><br>

  <div class="card">
  <b>Rejected requests:</b>
  <table>
  <% @counter3=0 %>
  <% @reservation.each do |reservation| %>  
    <tr>
    <% if reservation.user_id==current_user.id and reservation.confirmed==2%>
      <% @counter3+=1 %>  
      <% @current_book=Book.where(:id => reservation.book_id) %>  
      <div class="row"> 
        <div class="col"><li> Title: <%= @current_book[0][:title] %> </div>
         <% if reservation.comments!="" %>
          <div class="col">Notes: <%= reservation.comments %> </div>
        <% end %>
        <div class="col"><%= button_to book_path(@current_book[0][:id]), class: 'btn bg-transparent', method: :get do%><i class="fa fa-info-circle fa-lg"></i><%end%></li></div></li>
    </tr>
    <%end%>
  <% end %>
  <%if @counter3==0 %>
    <div class="col"> No rejected request yet.. </div>
  <%end%>
  </table>
  </div>
  <br><br>

app/views/users/show.html.erb
<%= render 'users/navbar' %>
<br>

<div class="container">
<% flash.each do |type, msg| %>
      <div class="alert alert-primary" role="alert" width="60%">
        Notification: <%= msg %>
      </div>
<% end %>
</div>

<% if current_user.is_library?%>
<%= render 'library' %>
<%end%>

<% if current_user.is_reader?%>
<%= render 'reader' %>
<%end%>