config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'
  get 'reservations/create'
  get 'reservations/destroy'
  get 'search', to: "books#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homepage#index'


  resources :books do
    resource :reservations, only: [:new, :create, :destroy]
  end 
  devise_for :users, :controllers => { :omniauth_callbacks =>"users/omniauth_callbacks", :registrations => "users/registrations"}
  resources :users, only: [:show]

  resources :reservations do
    put :is_confirmed, on: :member
    put :is_deleted, on: :member
  end
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reservations
    validates :title, presence: true
    validates :notes, presence: true
    validates :author, presence: true
    validates :isbn, presence: true, length: { is: 13 }, numericality: { only_integer: true }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :authenticate_user!, except: [:index,:search]
    before_action :check_owner, only: [:edit, :destroy, :update]

    def index
        @books = Book.all
    end

    def search 
        @books = Book.where("title LIKE?", "%" + params[:q] + "%")
    end

    def show
        @book = Book.find(params[:id])
        @user = User.all
        @reservation = Reservation.all
    end

    def new
        @book = Book.new
    end

    def edit
        @book = Book.find(params[:id])
    end

    def create
        authorize! :create, Book, message: "You are not authorized!"
        @book = Book.new(book_params)
        @book.owner=current_user.id
 
        if @book.save
            redirect_to @book
        else
            render 'new'
        end
    end

    def update
        authorize! :update, Book, message: "You are not authorized"
        @book = Book.find(params[:id])
        @book.owner=current_user.id
       
        if @book.update(book_params)
          redirect_to @book
        else
          render 'edit'
        end
    end

    def destroy
        authorize! :destroy, Book, message: "You are not authorized"
        @book = Book.find(params[:id])
        if Reservation.where(:book_id => @book.id).length!=0
            @book.reservations.destroy_all()
            @book.destroy
        else
            @book.destroy
        end

        redirect_to current_user
    end

    private
        def book_params
            params.require(:book).permit(:title, :author, :notes, :isbn, :owner=>current_user.id)
        end

    def check_owner
        @book = Book.find(params[:id])
        if current_user.id!=@book.owner
            redirect_to root_path
        end
    end
    
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div align="center" class="container" style="width: 80%">
<%= form_with model: @book, local: true do |form| %>
 
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </p>
 
 <p>
    <%= form.label :author %><br>
    <%= form.text_field :author, class: "form-control" %>
  </p>

  <p>
    <%= form.label :notes %><br>
    <%= form.text_area :notes, class: "form-control" %>
  </p>

  <p>
    <%= form.label :isbn %><br>
    <%= form.text_field :isbn, class: "form-control" %>
  </p>
 
  <p>
    <%= form.submit nil, class: 'btn btn-primary'%>
  </p>
</div>
<% end %>

app/views/books/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <div class="container-fluid">
    <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <% if !current_user %>
            <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="navbarDropdown" role="button">
              Login
            </a>
            <ul aria-labelledby="navbarDropdown" class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="/users/sign_up">Sign up</a>
              </li>
              <li>
                <hr class="dropdown-divider"/>
              </li>
              <li>
                <a class="dropdown-item" href="/users/sign_in">Sign in</a>
              </li>
            </ul>
          <% else %>
            <div class="row">
              <div class="col">
                <%= image_tag "user.png", style:"width:50px" %>
              </div>
              <div class="col">
                <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="navbarDropdown" role="button">Account</a>
                <ul aria-labelledby="navbarDropdown" class="dropdown-menu">
                  <li>
                    <a class="dropdown-item">
                      <%= button_to 'Profile', current_user, method: :get, class: "btn"%>
                    </a>
                  </li>
                  <hr>
                  <li>
                    <a class="dropdown-item">
                      <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn" %>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          <% end %>
        </li>
      </ul>
      
    </div>
    <%= button_to root_path, :method => :get, class: "btn" do%><i class="fa fa-arrow-circle-left fa-2x"></i>&emsp; Back to homepage<%end%>
  </div>
</nav>

app/views/books/edit.html.erb
<%= render 'books/navbar' %>
<div class="container">
  <div class="row">
    <div class="col">
      <%= image_tag 'black_book.png',style:"width:100%"%>
    </div>
    <div class="col-8">
    <br>
    <br>
    <div align="center" class="card" style="width: 100%">
        <h1>Edit Book</h1>
 
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/books/index.html.haml
= render 'books/navbar'

%h1 Listing Books 
- if can? :destroy, Book
  = link_to 'New book', new_book_path
- else
  = 'New book'
%table
  %tr
    %th Title
    %th Author
    %th Notes
    %th ISBN
    %th
  - @books.each do |book|
    %tr
      %td= book.title
      %td= book.author
      %td= book.notes
      %td= book.isbn
      - if can? :show, Book
        %td= link_to 'Show', book_path(book)
      -else 
        %td= 'Show'
      - if can? :edit, Book
        -if book.owner==current_user.id
          %td= link_to 'Edit', edit_book_path(book)
      - else 
        %td= 'Edit'
      - if can? :destroy, Book
        -if book.owner==current_user.id
          -if Reservation.where(:book_id => book.id).length!=0
            %td= link_to 'Destroy', book_path(book), :method => :delete, data: { confirm: 'You have some pending request for this book, are you sure you want to delete it?' }
          -elsif Reservation.where(:book_id => book.id).length==0
            %td= link_to 'Destroy', book_path(book), :method => :delete, data: { confirm: 'Are you sure?' }
      - else
        %td= 'Destroy'

app/views/books/new.html.erb
<%= render 'books/navbar' %>
<div class="container">
  <div class="row">
    <div class="col">
      <%= image_tag 'black_book.png',style:"width:100%"%>
    </div>
    <div class="col-8">
    <br>
    <br>
    <div align="center" class="card" style="width: 100%">
      <h1>Add a book</h1>
 
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<%= render 'books/navbar' %>
<br>

<div class="container">
<% if @books.length!=0 %>
  <h1> Results found: </h1>
  <br>


  <% @books.each do |book| %>
    <div class= "row">
      <div class="col-3">
        Title:
        <%= book.title %>
      </div>
      <div class="col">
        <%= button_to 'Show details', book_path(book), :method => :get, class:"btn btn-primary"%>
      </div>
    
    </div>
    <br><br>
  <% end %>  
<% else %>
<h1> No results found. </h1>
<% end %>
</div>

app/views/books/show.html.haml
= render 'books/navbar' 

.container
  .row
    .col
      = image_tag 'black_book.png',style:"width:100%"
    .col-8
      %br
      %br
      .card{:align => "center", :style => "width: 100%"}
        %br
        %h1 Details
        %hr
        

        %p
          %strong Title:
          = @book.title
        %p
          %strong Author:
          = @book.author

        %p
          %strong Notes:
          = @book.notes

        %p
          %strong ISBN:
          = @book.isbn

        %p
          %strong Status:
          -if Reservation.where(:book_id => @book.id).length==0
            ="available"
          -if Reservation.where(:book_id => @book.id).length!=0
            -@reservations=Reservation.where(:book_id => @book.id)
            -@counter=0
            -@reservations.each do |reservations|
              -if reservations.confirmed==1
                -@counter=1
            -if @counter==1
              ="borrowed"
            -else
              ="available"

        %p
          %strong Location:
          =User.find(@book.owner).address+", "+User.find(@book.owner).city
          

        %p 
          %iframe{:allowfullscreen => "", :height => "350", :loading => "lazy", :src => "https://www.google.com/maps/embed/v1/place?key=AIzaSyDm3kA0H6nEx18Xux8n-pWMtUVKupJNiIU&q="+User.find(@book.owner).address+","+User.find(@book.owner).city+",IT", :style => "border:0", :width => "90%"}
          

        .container 
          .row 
            
            .col
              - if can? :edit, Book
                -if @book.owner==current_user.id 
                  = button_to 'Edit', edit_book_path(@book), :method => :get, class: "btn btn-primary"
              %br
              .col
              - if can? :delete, Book
                -if @book.owner==current_user.id 
                  -if Reservation.where(:book_id => @book.id).length!=0
                    = button_to 'Delete book', book_path(@book), :method => :delete, data: { confirm: 'You have some pending request for this book, are you sure you want to delete it?' },  class: "btn btn-primary"
                  -elsif Reservation.where(:book_id => @book.id).length==0
                    = button_to 'Delete book', book_path(@book), :method => :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-primary"
          %br
          .row 
            
            - if current_user.is_reader?
              - @current_reservation=Reservation.where(:user_id => current_user.id, :book_id => @book.id)
              -if @current_reservation.length!=0
                -if @current_reservation[0][:confirmed]!=2
                  = button_to 'Cancel reservation request', reservation_path(@current_reservation[0][:id]), method: :delete, class: 'btn btn-danger'
                -else
                  = button_to 'Ask reservation', new_book_reservations_path(@book), class: "btn btn-primary", :method => :get
              -else
                = button_to 'Ask reservation', new_book_reservations_path(@book), class: "btn btn-primary", :method => :get
        
        %br