config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'
  get 'reservations/create'
  get 'reservations/destroy'
  get 'search', to: "books#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homepage#index'


  resources :books do
    resource :reservations, only: [:new, :create, :destroy]
  end 
  devise_for :users, :controllers => { :omniauth_callbacks =>"users/omniauth_callbacks", :registrations => "users/registrations"}
  resources :users, only: [:show]

  resources :reservations do
    put :is_confirmed, on: :member
    put :is_deleted, on: :member
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
    belongs_to :book
    belongs_to :user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
  end

  def create
    authorize! :create, Reservation, message: "You are not authorized!"
    id_book = params[:book_id]
    user_id = current_user.id
    @book = Book.find(id_book)
    @reservation = @book.reservations.create!(:comments =>
    params[:reservation][:comments],:user_id=> user_id, :confirmed => 0)
      
    redirect_to @current_user
      
  end

  def destroy
    authorize! :destroy, Reservation, message: "You are not authorized!"
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to current_user
  end

  def is_confirmed
    @reservation= Reservation.find(params[:id])
    @reservation.update(confirmed: 1)
    redirect_to current_user
  end

  def is_deleted
    @reservation= Reservation.find(params[:id])
    @reservation.update(confirmed: 2)
    redirect_to current_user
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/new.html.haml
= render 'books/navbar'

%br

.container{align: "center", style: "width: 50%"}
    %h2 Ask reservation
    %br
    = form_tag book_reservations_path, :method => :post do

        = label :reservation, :comments, 'Comment'
        = text_field :reservation, :comments, class:"form_control"

        %br
        %br
        = submit_tag 'Ask reservation', class:"btn btn-success"